/*
 * generated by Xtext
 */
package org.xtext.simple.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.simple.ui.internal.SimpleExpressionsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimpleExpressionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimpleExpressionsActivator.getInstance().getInjector(SimpleExpressionsActivator.ORG_XTEXT_SIMPLE_SIMPLEEXPRESSIONS);
	}
	
}
