/**
 * generated by Xtext 2.9.1
 */
package org.xtext.template.template.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XIfExpressionImpl;

import org.xtext.template.template.RichStringIf;
import org.xtext.template.template.TemplatePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rich String If</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RichStringIfImpl extends XIfExpressionImpl implements RichStringIf
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RichStringIfImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TemplatePackage.Literals.RICH_STRING_IF;
  }

} //RichStringIfImpl
