/*
 * generated by Xtext 2.14.0
 */
package org.xtext.mongobeans.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public class MongoBeansScopeProvider extends XbaseBatchScopeProvider {
}
