/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.httprouting.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.httprouting.RouteRuntimeModule;
import org.xtext.httprouting.RouteStandaloneSetup;
import org.xtext.httprouting.ide.RouteIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RouteIdeSetup extends RouteStandaloneSetup {
  @Override
  public Injector createInjector() {
    RouteRuntimeModule _routeRuntimeModule = new RouteRuntimeModule();
    RouteIdeModule _routeIdeModule = new RouteIdeModule();
    return Guice.createInjector(Modules2.mixin(_routeRuntimeModule, _routeIdeModule));
  }
}
