/*
* generated by Xtext
*/
package org.xtext.guicemodules;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GuiceModulesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.guicemodules.ui.internal.GuiceModulesActivator.getInstance().getInjector("org.xtext.guicemodules.GuiceModules");
	}
	
}
