/*
 * generated by Xtext
 */
package org.xtext.guicemodules.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

public class GuiceModulesQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
