/**
 * generated by Xtext 2.17.0
 */
package org.xtext.mongobeans.mongoBeans;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mongo Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mongobeans.mongoBeans.MongoProperty#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.mongobeans.mongoBeans.MongoProperty#getInlineType <em>Inline Type</em>}</li>
 *   <li>{@link org.xtext.mongobeans.mongoBeans.MongoProperty#isMany <em>Many</em>}</li>
 * </ul>
 *
 * @see org.xtext.mongobeans.mongoBeans.MongoBeansPackage#getMongoProperty()
 * @model
 * @generated
 */
public interface MongoProperty extends AbstractFeature
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(JvmTypeReference)
   * @see org.xtext.mongobeans.mongoBeans.MongoBeansPackage#getMongoProperty_Type()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getType();

  /**
   * Sets the value of the '{@link org.xtext.mongobeans.mongoBeans.MongoProperty#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(JvmTypeReference value);

  /**
   * Returns the value of the '<em><b>Inline Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inline Type</em>' containment reference.
   * @see #setInlineType(MongoBean)
   * @see org.xtext.mongobeans.mongoBeans.MongoBeansPackage#getMongoProperty_InlineType()
   * @model containment="true"
   * @generated
   */
  MongoBean getInlineType();

  /**
   * Sets the value of the '{@link org.xtext.mongobeans.mongoBeans.MongoProperty#getInlineType <em>Inline Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inline Type</em>' containment reference.
   * @see #getInlineType()
   * @generated
   */
  void setInlineType(MongoBean value);

  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see org.xtext.mongobeans.mongoBeans.MongoBeansPackage#getMongoProperty_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link org.xtext.mongobeans.mongoBeans.MongoProperty#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

} // MongoProperty
