/*
 * generated by Xtext 2.16.0
 */
package org.xtext.builddsl.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

public class BuildDSLQuickfixProvider extends XbaseQuickfixProvider {
}
