/*
 * generated by Xtext
 */
package org.xtext.template;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class TemplateRuntimeModule extends AbstractTemplateRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return TemplateValueConverterService.class;
	}
}
