/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.tortoiseshell.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

public class TortoiseShellQuickfixProvider extends XbaseQuickfixProvider {
}
