/*
* generated by Xtext
*/
package org.xtext.tortoiseshell.ui.contentassist;

import org.xtext.tortoiseshell.ui.contentassist.AbstractTortoiseShellProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TortoiseShellProposalProvider extends AbstractTortoiseShellProposalProvider {

}
