/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.template.template;

import org.eclipse.xtext.xbase.XForLoopExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rich String For Loop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.template.template.TemplatePackage#getRichStringForLoop()
 * @model
 * @generated
 */
public interface RichStringForLoop extends XForLoopExpression
{
} // RichStringForLoop
