/**
 * generated by Xtext 2.16.0
 */
package org.xtext.template.template;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rich String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.template.template.TemplatePackage#getRichString()
 * @model
 * @generated
 */
public interface RichString extends XBlockExpression
{
} // RichString
