/*
 * generated by Xtext 2.14.0
 */
package org.xtext.tortoiseshell.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.tortoiseshell.parser.antlr.internal.InternalTortoiseShellParser;
import org.xtext.tortoiseshell.services.TortoiseShellGrammarAccess;

public class TortoiseShellParser extends AbstractAntlrParser {

	@Inject
	private TortoiseShellGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTortoiseShellParser createParser(XtextTokenStream stream) {
		return new InternalTortoiseShellParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public TortoiseShellGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TortoiseShellGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
