/*
 * generated by Xtext 2.9.1
 */
package org.xtext.template.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.template.ui.internal.TemplateActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TemplateExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TemplateActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TemplateActivator.getInstance().getInjector(TemplateActivator.ORG_XTEXT_TEMPLATE_TEMPLATE);
	}
	
}
