/*
 * generated by Xtext
 */
package org.cradle.language.ui;

import org.cradle.language.MyInterface;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CradleUiModule extends org.cradle.language.ui.AbstractCradleUiModule {
	public CradleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@org.eclipse.xtext.service.SingletonBinding(eager=true)
	public Class<? extends MyInterface> bindMyInterface() {
		return MyInterface.ImplB.class;
	}
}
