/**
 * generated by Xtext 2.9.1
 */
package org.xtext.scripting.scripting.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XBlockExpressionImpl;

import org.xtext.scripting.scripting.Script;
import org.xtext.scripting.scripting.ScriptingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScriptImpl extends XBlockExpressionImpl implements Script
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScriptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ScriptingPackage.Literals.SCRIPT;
  }

} //ScriptImpl
