/*
 * generated by Xtext
 */
package org.xtext.tortoiseshell.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.tortoiseshell.ui.internal.TortoiseshellActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TortoiseShellExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TortoiseshellActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TortoiseshellActivator activator = TortoiseshellActivator.getInstance();
		return activator != null ? activator.getInjector(TortoiseshellActivator.ORG_XTEXT_TORTOISESHELL_TORTOISESHELL) : null;
	}

}
