/*
 * generated by Xtext
 */
package org.xtext.mongobeans.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mongobeans.parser.antlr.internal.InternalMongoBeansParser;
import org.xtext.mongobeans.services.MongoBeansGrammarAccess;

public class MongoBeansParser extends AbstractAntlrParser {

	@Inject
	private MongoBeansGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMongoBeansParser createParser(XtextTokenStream stream) {
		return new InternalMongoBeansParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MongoFile";
	}

	public MongoBeansGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MongoBeansGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
