/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.guicemodules.ide


/**
 * Use this class to register ide components.
 */
class GuiceModulesIdeModule extends AbstractGuiceModulesIdeModule {
}
