/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.guicemodules.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.guicemodules.GuiceModulesRuntimeModule;
import org.xtext.guicemodules.GuiceModulesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GuiceModulesIdeSetup extends GuiceModulesStandaloneSetup {
  @Override
  public Injector createInjector() {
    GuiceModulesRuntimeModule _guiceModulesRuntimeModule = new GuiceModulesRuntimeModule();
    GuiceModulesIdeModule _guiceModulesIdeModule = new GuiceModulesIdeModule();
    return Guice.createInjector(Modules2.mixin(_guiceModulesRuntimeModule, _guiceModulesIdeModule));
  }
}
