/*
 * generated by Xtext 2.19.0
 */
package org.xtext.scripting.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

public class ScriptingQuickfixProvider extends XbaseQuickfixProvider {
}
