/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.tortoiseshell.ide


/**
 * Use this class to register ide components.
 */
class TortoiseShellIdeModule extends AbstractTortoiseShellIdeModule {
}
