/*
 * generated by Xtext
 */
package org.xtext.simple;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimpleExpressionsRuntimeModule extends org.xtext.simple.AbstractSimpleExpressionsRuntimeModule {

}
