/*
* generated by Xtext
*/
package org.xtext.scripting.ui.contentassist;

import org.xtext.scripting.ui.contentassist.AbstractScriptingProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ScriptingProposalProvider extends AbstractScriptingProposalProvider {

}
