/*
 * generated by Xtext
 */
package org.xtext.guicemodules.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider;
import org.xtext.guicemodules.guiceModules.Binding;
import org.xtext.guicemodules.guiceModules.Key;
import org.xtext.guicemodules.guiceModules.Module;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class GuiceModulesLabelProvider extends XbaseLabelProvider {

	@Inject
	public GuiceModulesLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Module m) {
		return m.getName();
	}

	String text(Binding binding) {
		StringBuilder sb = new StringBuilder();
		Key key = binding.getFrom();
		if (key.getAnnotation()!=null) {
			sb.append("@").append(key.getAnnotation().getAnnotation().getSimpleName()).append(" ");
		}
		sb.append(key.getType().getSimpleName());
		return sb.toString();
	}
}
