/*
 * generated by Xtext 2.19.0
 */
package org.xtext.httprouting.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public class RouteScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
