if(args.size == 0)
	println('Missing args: Specify file names')

import java.io.File
import com.google.common.io.*
import com.google.common.base.Charsets

for (arg : args) {
	val lines = Files::readLines(new File(arg), Charsets::UTF_8)
	var wordsInFile = lines
		.map[ split('\\s*').size ]
		.reduce[ a, b | a + b ]
	println('File ' + arg + ': ' 
		+ wordsInFile + ' words, ' + lines.size + ' lines.'
	)
}
