/*
 * generated by Xtext 2.14.0
 */
package org.xtext.template.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

public class TemplateQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
