/*
 * generated by Xtext 2.19.0
 */
package org.xtext.scripting.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public class ScriptingScopeProvider extends XbaseBatchScopeProvider {
}
