/*
* generated by Xtext
*/
package org.cradle.language.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cradle.language.services.CradleGrammarAccess;

public class CradleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CradleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cradle.language.parser.antlr.internal.InternalCradleParser createParser(XtextTokenStream stream) {
		return new org.cradle.language.parser.antlr.internal.InternalCradleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CradleFile";
	}
	
	public CradleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CradleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
