/**
 * generated by Xtext
 */
package org.xtext.mongobeans.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
@SuppressWarnings("all")
public class MongoBeansDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
