/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.template.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public class TemplateScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
