grammar org.xtext.tortoiseshell.TortoiseShell with org.eclipse.xtext.xbase.Xbase

import "http://www.eclipse.org/xtext/xbase/Xbase"
generate tortoiseShell "http://www.xtext.org/tortoiseshell/TortoiseShell"

Program :
	body=Body
	subPrograms+=SubProgram*;
	
SubProgram:
	'sub' name=ValidID
	(parameters += FullJvmFormalParameter)*
	body=Body;

Body returns XBlockExpression:
	{XBlockExpression}
	'begin'
	(expressions+=XExpressionInsideBlock ';'?)*
	'end';
	
Executable:
	Program | SubProgram;