/*
 * generated by Xtext 2.9.1
 */
package org.xtext.builddsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public class BuildDSLScopeProvider extends XbaseBatchScopeProvider {
}
