/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.httprouting.route.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.httprouting.route.AbstractDeclaration;
import org.xtext.httprouting.route.RoutePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractDeclarationImpl extends MinimalEObjectImpl.Container implements AbstractDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RoutePackage.Literals.ABSTRACT_DECLARATION;
  }

} //AbstractDeclarationImpl
